Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/gpfs/home1/won0316/_Capstone/1_Git/Capstone_uos/unit_model/scripts/convert_excel_to_csv.py", line 9, in <module>
    pretrain_name = os.getenv("SOURCE_NAME", cfg.SOURCE_NAME)
                                             ^^^^^^^^^^^^^^^
AttributeError: module 'config.config' has no attribute 'SOURCE_NAME'. Did you mean: 'SOURCE_NAMES'?
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home1/won0316/anaconda3/envs/toxcast_env/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python3', '-u', '-m', 'scripts.convert_excel_to_csv']' returned non-zero exit status 1.
